
let space_questions = [
    {
        question: 'Which of the following phenomena cannot be observed on the surface of the Moon?',
        option1: 'Rising and setting of the Sun',
        option2: 'Solar eclipse',
        option3: 'Motion of comets',
        option4: 'Twinkling of stars',
        answer: 4,
    },
    {
        question: 'Which of the following planets has a revolution time which is shorter than its rotation time?',
        option1: 'Jupiter',
        option2: 'Venus',
        option3: 'Mars',
        option4: 'Uranus',
        answer: 2,
    },
    {
        question: " Which female astronaut spent the maximum time in space?",
        option1: "Lisa Norwak",
        option2: "Kalpana Chawla",
        option3: "Sunita Williams",
        option4: "None of these",
        answer: 3,
    },
    {
        question: "Which of the following planets has a lesser rotation time than the Earth?",
        option1: "Jupiter",
        option2: "Mars",
        option3: "Mercury",
        option4: "Venus",
        answer: 1,
    },
    {
        question: "The asteroid belt is located between which two planets in the solar system?",
        option1: "Earth and Mars",
        option2: "Mars and Jupiter",
        option3: "Jupiter and Saturn",
        option4: "Saturn and Uranus",
        answer: 2,
    },
    {
        question: " A star of which colour can be said to be the coolest",
        option1: "Yellow",
        option2: "Blue",
        option3: "Red",
        option4: "Black",
        answer: 3,
    },
    {
        question: "Which of the following Planets have no moons?",
        option1: "Pluto and Mercury",
        option2: "Mars and Venus",
        option3: "Mercury and Venus",
        option4: "Pluto and Mars",
        answer: 3,
    },
    {
        question: "Which planet has the solar system's highest mountain Olympus Mons?",
        option1: "Jupiter",
        option2: "Uranus",
        option3: "Venus",
        option4: "Mars",
        answer: 4,
    },
    {
        question: "‘New Horizons’ spacecraft was launched by NASA to study which of the following planet?",
        option1: "Mars",
        option2: "Pluto",
        option3: "Jupiter",
        option4: "Mercury",
        answer: 2,
    },
    {
        question: "Which of the following is the nearest galaxy to the Milky Way?",
        option1: "Andromeda galaxy",
        option2: "Cartwheel galaxy",
        option3: "Pinwheel galaxy",
        option4: "Whirlpool galazy",
        answer: 1,
    },
]

let vedic_questions = [
    {
        question: 'what is the value of 93 * 86',
        option1: '8098',
        option2: '9098',
        option3: '7998',
        option4: '9808',
        answer: 3,
    },
    {
        question: 'what is the value of 395 x 11 ',
        option1: '4535',
        option2: '4345',
        option3: '5345',
        option4: '3545',
        answer: 2,
    },
    {
        question: 'what is the square of 35 ',
        option1: '125',
        option2: '1225',
        option3: '1525',
        option4: '5215',
        answer: 2,
    },
    {
        question: 'what is the value of 6084 ÷ 5',
        option1: '121.68',
        option2: '8064',
        option3: '1216.8',
        option4: '156.3',
        answer: 3,
    },
    {
        question: 'what is the value of 73624 ÷ 25',
        option1: '294.496',
        option2: '294496',
        option3: '29449.6',
        option4: '2944.96',
        answer: 4,
    },
    {
        question: 'what is the value of 5421 x 33',
        option1: '178893',
        option2: '1788993',
        option3: '179883',
        option4: '198873',
        answer: 1,
    },
    {
        question: 'what is the value of 1759 ÷ 25',
        option1: '703.6',
        option2: '7036',
        option3: '70.36',
        option4: '7036.0',
        answer: 3,
    },
    {
        question: 'what is the square of 115',
        option1: '12025',
        option2: '13225',
        option3: '10025',
        option4: '12125',
        answer: 2,
    },
    {
        question: 'Find the square of 112',
        option1: '11244',
        option2: '12544',
        option3: '13544',
        option4: '14544',
        answer: 2,
    },
    {
        question: '175616 is the cube for which two digit number',
        option1: '46',
        option2: '56',
        option3: '66',
        option4: '66',
        answer: 2,
    },
]

let history_questions = [
    {
        question: "In which year and at which place, India’s national anthem was sung for the first time?",
        option1: '1911, Kolkata',
        option2: '1912, Lucknow',
        option3: '1913, Delhi',
        option4: '1914, Bombay',
        answer: 1,
    },
    {
        question: "In which year, Partition of Bengal was annulled?",
        option1: '1909',
        option2: '1910',
        option3: '1911',
        option4: '1912',
        answer: 3,
    },
    {
        question: "The MIG series of Super fighters have come to India from which of the following ________ ?",
        option1: 'Russia',
        option2: 'USA',
        option3: 'UK',
        option4: 'France',
        answer: 1,
    },
    {
        question: "The Indian Independence League (1942) was founded by whom in Tokyo?",
        option1: 'Taraknath Das',
        option2: 'Subhash Chandra Bose',
        option3: 'Chandra Shekhar Azad',
        option4: 'Rash Bihari Bose',
        answer: 4,
    },
    {
        question: "Who of the following is referred to as “Rough, crude but intelligent Chitpavan Brahmin”?",
        option1: 'Bajirao I',
        option2: 'Balaji Biswanath',
        option3: 'Balaji Bajirao II',
        option4: 'Sivaji',
        answer: 2,
    },
    {
        question: "Who is the author of Vande Mataram?",
        option1: 'Mahatma Gandhi',
        option2: 'Rabindranath Tagore',
        option3: 'Bankim Chandra Chatterjee',
        option4: 'Sarat Chandra Chatterjee',
        answer: 3,
    },
    {
        question: "Who is regarded as as the ‘father of modern India’",
        option1: 'Mahatma Gandhi',
        option2: 'Raja Ram Mohan Roy',
        option3: 'Bhagat Singh',
        option4: 'Swami Dayananda Saraswati',
        answer: 2,
    },
    {
        question: "The Mughal General, who decisively defeated Shivaji and forced him to conclude the Treaty of Purandar, was",
        option1: ' Shaista Khan',
        option2: 'Dilir Khan',
        option3: 'Prince Muazzam',
        option4: 'Mirza Raja Jai Singh',
        answer: 2,
    },
    {
        question: "The Mughal General, who decisively defeated Shivaji and forced him to conclude the Treaty of Purandar, was",
        option1: ' Shaista Khan',
        option2: 'Dilir Khan',
        option3: 'Prince Muazzam',
        option4: 'Mirza Raja Jai Singh',
        answer: 2,
    },
    {
        question: "Shivaji ceded the forts to the Mughals by the treaty of",
        option1: 'Chittor',
        option2: 'Pune',
        option3: 'Purandar',
        option4: 'Torna',
        answer: 2,
    },
]

let gscience_questions = [
    {
        question: "Electric bulb filament is made of",
        option1: 'Copper',
        option2: 'Aluminum',
        option3: 'Lead',
        option4: 'Tungsten',
        answer: 4,
    },
    {
        question: "Brass gets discoloured in air because of the presence of which of the following gases in air?",
        option1: 'Oxygen',
        option2: 'Hydrogen Sulphide',
        option3: 'Carbon dioxide',
        option4: 'Nitrogen',
        answer: 2,
    },
    {
        question: "Which of the following is a non metal that remains liquid at room temperature?",
        option1: 'Phosphorous',
        option2: 'Bromine',
        option3: 'Chlorine',
        option4: 'Helium',
        answer: 2,
    },
    {
        question: "Which of the following is used in pencils?",
        option1: 'Graphite',
        option2: 'Silicon',
        option3: 'Charcoal',
        option4: 'Phosphorous',
        answer: 1,
    },
    {
        question: "Washing soda is the common name for",
        option1: 'Sodium Carbonate',
        option2: 'Calcium Bicarbonate',
        option3: 'Sodium Bicarbonate',
        option4: 'Calcium Carbonate',
        answer: 1,
    },
    {
        question: "Quartz crystals normally used in quartz clocks etc. is chemically",
        option1: 'Germanium Oxide',
        option2: 'Silicon Dioxide',
        option3: 'A mixture of Germanium Oxide and Silicon dioxide',
        option4: 'Sodium Silicate',
        answer: 2,
    },
    {
        question: "Which of the gas is not known as green house gas?",
        option1: 'Methane',
        option2: 'Nitrous oxide',
        option3: 'Carbon dioxide',
        option4: 'Hydrogen',
        answer: 4,
    },
    {
        question: "Which of the gas is not known as green house gas?",
        option1: 'Methane',
        option2: 'Nitrous oxide',
        option3: 'Carbon dioxide',
        option4: 'Hydrogen',
        answer: 4,
    },
    {
        question: "The hardest substance available on earth is",
        option1: 'Gold',
        option2: 'Vibranium',
        option3: 'Diamond',
        option4: 'Platinum',
        answer: 3,
    },
    {
        question: "Which of the following is used as a lubricant?",
        option1: 'Graphite',
        option2: 'Silica',
        option3: 'Iron Oxide',
        option4: 'Diamond',
        answer: 1,
    },
]

let caffairs_questions = [
    {
        question: "Which food delivery platform is set to onboard over 36000 street vendors under PM SVANidhi scheme?",
        option1: 'Zomato',
        option2: 'Swiggy',
        option3: 'Uber Eats',
        option4: 'Groffers',
        answer: 2,
    },
    {
        question: "Which is the state bird of Uttar Pradesh, that has been adopted as new logo of NOIDA international airport?",
        option1: 'Sparrow',
        option2: 'Lesser Falcon',
        option3: 'Sarus Crane',
        option4: 'Peacock',
        answer: 3,
    },
    {
        question: "India’s first-ever driverless train operations has been inaugurated in which Metro rail service?",
        option1: 'Delhi Metro',
        option2: 'Lucknow Metro',
        option3: 'Chennai Metro',
        option4: 'Cochin Metro',
        answer: 1,
    },
    {
        question: "The PM CARES Fund Trust has allocated Rs 201 crores for installation of which equipment?",
        option1: 'Oxygen Generation Plants',
        option2: 'Air Purifiers',
        option3: 'RO- Water Purifiers',
        option4: 'Make Shift Hospitals',
        answer: 1,
    },
    {
        question: "India’s first undersea tunnel is being constructed in which city?",
        option1: 'Chennai',
        option2: 'Cochin',
        option3: 'Mumbai',
        option4: 'Kolkata',
        answer: 3,
    },
    {
        question: "Which Ministry has mandated companies to disclose their investments in cryptocurrencies?",
        option1: 'Ministry of Finance',
        option2: 'Ministry of Corporate Affairs',
        option3: 'Ministry of Home Affairs',
        option4: 'Ministry of Electronics and IT',
        answer: 2,
    },
    {
        question: "Which state has recently launched a solar-based electrification programme for its rural households?",
        option1: 'Uttar Pradesh',
        option2: 'Odisha',
        option3: 'Assam',
        option4: 'Goa',
        answer: 4,
    },
    {
        question: "The Sardar Sarovar Dam is a terminal Dam built on which river?",
        option1: 'Sutlej',
        option2: 'Narmada',
        option3: 'Beas',
        option4: 'Chenab',
        answer: 2,
    },
    {
        question: "Which is India’s first certified organic fruit?",
        option1: 'Apple',
        option2: 'Strawberry',
        option3: 'Kiwi',
        option4: 'Banana',
        answer: 3,
    },
    {
        question: "India has decided to set up one-million-dollar facility for academic collaboration with countries of which region?",
        option1: 'Europe',
        option2: 'South America',
        option3: 'Arab',
        option4: 'Australia',
        answer: 3,
    },
]

let nature_questions = [
    {
        question: "Every food chain in the ecosystem begins with………. which are the original source of food.",
        option1: 'Saprophytes',
        option2: 'Parasites',
        option3: 'Producers',
        option4: 'Herbivores',
        answer: 3,
    },
    {
        question: "We should reduce the use of the plastic bags, bottles etc. because:",
        option1: 'They are not durable',
        option2: 'They are non-biodegradable',
        option3: 'They are made of toxic materials',
        option4: 'They react with the atmospheric gases',
        answer: 3,
    },
    {
        question: "Which among the following statements is incorrect in view of the plants?",
        option1: 'They convert the solar energy into mechanical energy',
        option2: 'They prepare their food from organic compounds',
        option3: 'They are also called producers',
        option4: 'They are the initial source of energy in a food chain',
        answer: 2,
    },
    {
        question: "In a food chain the second trophic level is occupied by:",
        option1: 'Carnivores',
        option2: 'Autotrophs',
        option3: 'Herbivores',
        option4: 'Producers',
        answer: 3,
    },
    {
        question: "Green plants utilize ……… percent of sun’s energy to prepare their food by the process of photosynthesis?",
        option1: '1 percent',
        option2: '10 percent',
        option3: '20 percent',
        option4: '99 percent',
        answer: 1,
    },
    {
        question: "Which of the following radiations is responsible for the conversion of atmospheric oxygen to ozone?",
        option1: 'Gamma radiations',
        option2: 'Cosmic radiations',
        option3: 'Infrared radiations',
        option4: 'Ultraviolet radiations',
        answer: 4,
    },
    {
        question: "Global warming is a phenomenon related to:",
        option1: 'Evaporation',
        option2: 'Ecological balance',
        option3: 'Greenhouse effect',
        option4: 'Desertification',
        answer: 3,
    },
    {
        question: "The portion of earth and its environment which can support life is known as ",
        option1: 'Crust',
        option2: 'Biosphere',
        option3: 'Exosphere',
        option4: 'Atmosphere',
        answer: 3,
    },
    {
        question: "Soil errosion can be prevented by ",
        option1: 'Deforestation',
        option2: 'Afforestation',
        option3: 'Overgrazing',
        option4: 'Removal of vegetation',
        answer: 2,
    },
    {
        question: "What is troposphere",
        option1: 'Portion of Air',
        option2: 'Portion of Water',
        option3: 'Lowest layer of atmosphere',
        option4: 'portion of sky',
        answer: 3,
    },

]

let pysch_questions = [
    {
        question: "Where the word 'psychology' does come from?",
        option1: 'Italian',
        option2: 'Greek',
        option3: 'Latin',
        option4: 'None of the above',
        answer: 2,
    },
    {
        question: "Psychology is said to be the scientific study of _____ and ______.",
        option1: 'Behavior, mental processes',
        option2: 'Mental illness, Mental health',
        option3: 'Physical states, mental states',
        option4: 'None of the above',
        answer: 1,
    },
    {
        question: "Which of the following part of the brain sends signals 'alert' to the higher centers in response to incoming messages?",
        option1: 'Reticular formation',
        option2: 'Hippocampus',
        option3: 'Limbic system',
        option4: 'Amygdala',
        answer: 1,
    },
    {
        question: "Which of the following is an example of the negative attitude towards people?",
        option1: 'Stereotype',
        option2: 'Prototype',
        option3: 'Prejudice',
        option4: 'Discrimination',
        answer: 3,
    },
    {
        question: "Which of the following Greek philosopher believed that knowledge is acquired through learning and experience?",
        option1: 'Aristotle',
        option2: 'Plato',
        option3: 'Archimedes',
        option4: 'None of the above',
        answer: 1,
    },
    {
        question: "Which of the following is a belief that the mind is fundamentally different from the body?",
        option1: 'Mindism',
        option2: 'Specialism',
        option3: 'Centralism',
        option4: 'Mind-body Dualism',
        answer: 4,
    },
    {
        question: "The process of using psychological methods by a trained psychologist for helping people with psychological problems is called as -",
        option1: 'Psychoanalysis',
        option2: 'Psychotherapy',
        option3: 'Psychiatry',
        option4: 'None of the above',
        answer: 2,
    },
    {
        question: "Which of the following is a part of the psychosocial domain?",
        option1: 'Judgment',
        option2: 'Style of behaving',
        option3: 'Memory',
        option4: 'Motor skills',
        answer: 2,
    },
    {
        question: "Which of the following is not a diagnosable sleep disorder?",
        option1: 'Insomnia',
        option2: 'Sleep terror',
        option3: 'Somnambulism',
        option4: 'Somniloquy',
        answer: 4,
    },
    {
        question: "The method of gathering information about the brain that indicates the overall activity of the brain is called as ",
        option1: 'Positron emission tomography',
        option2: 'Electrical stimulation',
        option3: 'Electroencephalogram',
        option4: 'None of the above',
        answer: 1,
    },
]

let fitness_questions = [
    {
        question: "Which One Of These Exercises Is Effective For Weight Loss?",
        option1: 'Cardio',
        option2: 'Yoga',
        option3: 'Strength exercises',
        option4: 'Balance exercises',
        answer: 1,
    },
    {
        question: "What Does HIIT Stand For?",
        option1: 'Heat',
        option2: 'High-interval intensity training',
        option3: 'High-interval intensity therapy',
        option4: 'High-intensity interval training',
        answer: 4,
    },
    {
        question: "How Do You Call The Layer Of Fat Around Your Waistline?",
        option1: 'Muffin top',
        option2: 'Beer belly',
        option3: 'Love handles',
        option4: 'Tummy',
        answer: 3,
    },
    {
        question: "Which Piece Of Equipment Will Be Useless For The Basic Squat?",
        option1: 'Dumbbells',
        option2: 'Bar',
        option3: 'Ankle weights',
        option4: 'Foam roller',
        answer: 3,
    },
    {
        question: "The percentage of fat,bone,water and muscle in human body is called",
        option1: 'Muscular endurance',
        option2: 'Muscular strength',
        option3: 'Body composition',
        option4: 'Flexibility',
        answer: 3,
    },
    {
        question: "The range of motion through a joint is known as what?",
        option1: 'Stretching',
        option2: 'Flexibility',
        option3: 'Agility',
        option4: 'Balance',
        answer: 2,
    },
    {
        question: "The ability of muscles to exert force on an object.",
        option1: 'Strength',
        option2: 'Power',
        option3: 'Speed',
        option4: 'Endurance',
        answer: 1,
    },
    {
        question: "Cardiorespiratory Endurance is",
        option1: "the body's ability to push or pull with all its force",
        option2: 'the ability to move a joint through its full range of motion',
        option3: 'the ability of the heart and lungs to supply oxygen to the body',
        option4: "the body's response to a flexibility program",
        answer: 3,
    },
    {
        question: "What does RICE stand for?",
        option1: "Whole Grains",
        option2: 'Remove, Ice, Cold, Exercise ',
        option3: 'Reduce Impact, Carry Energy',
        option4: "Rest, Ice, Compression, Elevation",
        answer: 4,
    },
    {
        question: "The amount of time it takes to make a physical response",
        option1: "Speed",
        option2: 'Cardio-respiratory Endurance',
        option3: 'Agility',
        option4: "Reaction Time",
        answer: 4,
    },
]